---
title: "git_01"
author: "Maryana Maayah"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves    
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!   


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Nature’s first green is gold,  
Her hardest hue to hold.  
Her early leaf’s a flower;  
But only so an hour.  
Then leaf subsides to leaf.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun." 
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Stay, I said  
to the cut flowers.  
They bowed  
their heads lower.  
  
Stay, I said to the spider,  
who fled.  
  
Stay, leaf.  
It reddened,  
embarrassed for me and itself.  
  
Stay, I said to my body.  
It sat as a dog does,  
obedient for a moment,  
soon starting to tremble.  
  
Stay, to the earth  
of riverine valley meadows,  
of fossiled escarpments,  
of limestone and sandstone.  
It looked back  
with a changing expression, in silence.  
  
Stay, I said to my loves.  
Each answered,  
Always.  
